name: Cron Scraping

on:
  schedule:
    - cron: '0 23 * * *' ## 6PM COLOMBIA
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint
        run: |
          curl -i -X GET "https://web-scraping-api-sooty.vercel.app/web-scraping-api-requests/scraping" \
               -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
               -H "User-Agent: GitHub-Actions-Bot"
